import { fauxAssistantMessage } from "@earendil-works/pi-ai";
import type { AgentMessage } from "@earendil-works/pi-agent-core";
import type { MessageRecord } from "../db/messages.ts";

/**
 * Spec §5.1 hydration: completed thread rows → agent conversation turns.
 *
 * Customer rows become user messages. Assistant rows are synthesized via
 * fauxAssistantMessage — pi-ai transforms provider-foreign assistant turns
 * when sending to the active provider, so replies generated by other models
 * (or the echo agent) remain valid history.
 */
export function hydrateThreadHistory(records: MessageRecord[]): AgentMessage[] {
  const messages: AgentMessage[] = [];
  for (const record of records) {
    if (record.role === "customer") {
      messages.push({
        role: "user",
        content: record.content,
        timestamp: record.createdAt,
      });
    } else if (record.role === "assistant") {
      messages.push(fauxAssistantMessage(record.content, { timestamp: record.createdAt }));
    }
    // 'system' rows are operational markers, not conversation turns.
  }
  return messages;
}

/** The claimed anchor + coalesced follow-ups as user turns for this run. */
export function buildPromptMessages(
  anchor: MessageRecord,
  followUps: MessageRecord[],
): AgentMessage[] {
  return [anchor, ...followUps].map((record) => ({
    role: "user" as const,
    content: record.content,
    timestamp: record.createdAt,
  }));
}
