/** Operator commands for validating, searching, and reporting on wiki/*.md. */
import { join } from "node:path";
import { LocalWikiConnector } from "../src/connectors/wiki.ts";
import { loadWikiCorpus, type WikiCorpus } from "../src/knowledge/wiki.ts";

const TOTAL_TICKETS = 250;

function existingCoverageTitles(markdown: string): Map<number, string> {
  const titles = new Map<number, string>();
  for (const line of markdown.split(/\r?\n/)) {
    const match = line.match(/^\|\s*FW-(\d{3})\s*\|\s*([^|]*?)\s*\|/);
    if (match !== null) titles.set(Number(match[1]), match[2].trim());
  }
  return titles;
}

function escapeCell(value: string): string {
  return value.replaceAll("|", "/").replaceAll("\n", " ");
}

export function renderCoverage(corpus: WikiCorpus, previous = ""): string {
  const titles = existingCoverageTitles(previous);
  const lines = [
    "# Ticket coverage",
    "",
    "Generated by `deno task wiki:check -- --coverage` directly from the hidden evidence comments in `wiki/*.md`: which pages reference each ticket; tickets no page references are listed at the end.",
    "",
    "| Ticket | Title | Referenced by |",
    "|---|---|---|",
  ];
  const uncited: number[] = [];
  for (let ticket = 1; ticket <= TOTAL_TICKETS; ticket++) {
    const pages = corpus.coverage.get(ticket) ?? [];
    if (pages.length === 0) uncited.push(ticket);
    lines.push(
      `| FW-${String(ticket).padStart(3, "0")} | ${
        escapeCell(titles.get(ticket) ?? "")
      } | ${pages.join(", ")} |`,
    );
  }
  lines.push(
    "",
    `**Not referenced (${uncited.length}):** ${
      uncited.length === 0
        ? "none"
        : uncited.map((ticket) => `FW-${String(ticket).padStart(3, "0")}`).join(
          ", ",
        )
    }`,
    "",
  );
  return lines.join("\n");
}

function queryFromArgs(args: string[]): string {
  const at = args.indexOf("--search");
  if (at < 0) return "";
  return args.slice(at + 1).filter((arg) => arg !== "--").join(" ").trim();
}

if (import.meta.main) {
  const path = Deno.env.get("KNOWLEDGE_BASE_PATH") || "./wiki";
  const query = queryFromArgs(Deno.args);
  if (query !== "") {
    const connector = new LocalWikiConnector(path, { logRequests: false });
    try {
      const results = await connector.search(query, 5);
      console.log(
        `Wiki ${connector.revision} · ${connector.articleCount} articles · query: ${query}`,
      );
      if (results.length === 0) console.log("No relevant wiki articles.");
      for (const [index, result] of results.entries()) {
        console.log(
          `${index + 1}. ${result.article.id} · ${
            result.score.toFixed(2)
          } · ${result.article.source} (${result.article.page})`,
        );
      }
    } finally {
      connector.close();
    }
  } else {
    const corpus = loadWikiCorpus(path);
    console.log(
      `Wiki OK: ${corpus.pages.length} pages, ${corpus.articles.length} articles, ` +
        `${corpus.coverage.size}/${TOTAL_TICKETS} tickets referenced, revision ${corpus.revision}`,
    );
    if (Deno.args.includes("--coverage")) {
      const output = join(path, "coverage.md");
      let previous = "";
      try {
        previous = Deno.readTextFileSync(output);
      } catch (error) {
        if (!(error instanceof Deno.errors.NotFound)) throw error;
      }
      Deno.writeTextFileSync(output, renderCoverage(corpus, previous));
      console.log(`Coverage written: ${output}`);
    }
  }
}
